# Generated by Django 5.2.17 on 2026-09-10 02:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=225)),
                ('major', models.CharField()),
                ('year_grad', models.IntegerField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
