# Generated by Django 5.2.17 on 2026-09-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('elementary', 'Elementary'), ('junior', 'Junior'), ('senior', 'Senior'), ('bachelor', 'Bachelor'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='year_start',
            field=models.IntegerField(default=2026),
        ),
    ]
