# Generated by Django 5.2.17 on 2026-09-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_education_category_education_year_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_grad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
    